name: docker test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dockertest:
    name: Run Api Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: |
        docker compose build
        docker compose up
      working-directory: 'src/.'

