name: docker test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dockertest:
    name: Run Api Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: |
        docker compose build
        docker compose up -d
      working-directory: 'src/.'
      
    - name: Run tests
      run: dotnet test 'src/WebApp.ApiTests' /p:CollectCoverage=true /p:Threshold=0%2c0%2c0 /p:ThresholdType=line%2cbranch%2cmethod
