name: publish swagger page

on:
  workflow_dispatch:

jobs:     
  publishArtifact:
    name: Publish API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: dotnet publish 'src/WebApp.Api' -c Release --output ./Release 
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore 'src/.'
    
    - name: Generate swagger.json
      run: | 
        dotnet new tool-manifest
        dotnet tool install --version 6.5.0 Swashbuckle.AspNetCore.Cli
        dotnet swagger tofile --output swagger.json ./Release/WebApp.Api.dll v1
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: swaggerDoku
        path: ./swagger.json
        retention-days: 1
