name: deploy CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore 'src/.'
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'src/.'
      
  tests:
    name: UnitTests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run Tests
      run: | 
            dotnet build --no-restore 'src/.'
            dotnet test 'src/WebApp.UnitTests' --filter UnitTest /p:CollectCoverage=true /p:Threshold=0%2c0%2c0 /p:ThresholdType=line%2cbranch%2cmethod
      
  UploadArtifact:
    name: Publich and Build Artifact
    runs-on: ubuntu-latest
    needs: [build, tests]
    steps:
    - name: Publish
      run: dotnet publish 'src/WebApp.Api' -c Release --output ./Release
      working-directory: 'src/.'
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: publishtest
        path: ./Release
  
    
