name: deploy CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore 'src/.'
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'src/.'
      
      
  dotnetFormat:
    name: Dotnet Format
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
    
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format
        run: dotnet format 'src/.' --verify-no-changes --no-restore
      
      
  unittests:
    name: Run UnitTests
    runs-on: ubuntu-latest
    needs: [build, dotnetFormat]
    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: dotnet test 'src/WebApp.UnitTests' --filter UnitTest /p:CollectCoverage=true /p:Threshold=0%2c0%2c0 /p:ThresholdType=line%2cbranch%2cmethod
    
    
  apitests:
    name: Run Api Tests
    runs-on: ubuntu-latest
    needs: [build, dotnetFormat]
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: |
        docker compose build
        docker compose up -d
      working-directory: 'src/.'
      
    - name: Run tests
      run: | 
        $env:API_BASE_URL="http://localhost:9001"
        dotnet test /p:CollectCoverage=true /p:Threshold=0%2c0%2c0 /p:ThresholdType=line%2cbranch%2cmethod
      working-directory: 'src/WebApp.ApiTests/.'
      
      
  publishArtifact:
    name: Publish API
    runs-on: ubuntu-latest
    needs: [unittests, apitests]
    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: dotnet publish 'src/WebApp.Api' -c Release --output ./Release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: publishApi
        path: ./Release
        retention-days: 1
  
  
  createApiDoku:
    name: Create Api-Doku
    runs-on: ubuntu-latest
    needs: [publishArtifact]
    steps:
    - uses: actions/checkout@v3
    
    - name: LoadArtifact
      uses: actions/download-artifact@v3
      with:
        name: publishApi
        path: ./Release
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore 'src/.'
    
    - name: Generate swagger.json
      run: | 
        dotnet new tool-manifest
        dotnet tool install --version 6.5.0 Swashbuckle.AspNetCore.Cli
        dotnet swagger tofile --output swagger.json ./Release/WebApp.Api.dll v1
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: swaggerDoku
        path: ./swagger.json
        retention-days: 1
        
  
  deployApiDoku:
    name: Deploy Api-Doku
    runs-on: ubuntu-latest
    needs: [createApiDoku]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: swaggerDoku
        path: ./Swagger
    
    - name: Display files
      run: ls -R
      working-directory: ./Swagger
  
  
  deployArtifact:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: [publishArtifact]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: publishApi
        path: ./Release
    
    - name: Display files
      run: ls -R
      working-directory: ./Release
